//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberClub.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CyberClub.Resources.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Process failed. Possibly, some required parameters are not set or the chosen name is already used..
        /// </summary>
        internal static string AccountFailMissingParamsOrNameAlreadyUsed {
            get {
                return ResourceManager.GetString("AccountFailMissingParamsOrNameAlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Added successfully..
        /// </summary>
        internal static string AddedSuccessfully {
            get {
                return ResourceManager.GetString("AddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Addition failed..
        /// </summary>
        internal static string AddError {
            get {
                return ResourceManager.GetString("AddError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Database error..
        /// </summary>
        internal static string DBError {
            get {
                return ResourceManager.GetString("DBError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete account?.
        /// </summary>
        internal static string DeleteAccountPrompt {
            get {
                return ResourceManager.GetString("DeleteAccountPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete developer?.
        /// </summary>
        internal static string DeleteDeveloperPrompt {
            get {
                return ResourceManager.GetString("DeleteDeveloperPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete game?.
        /// </summary>
        internal static string DeleteGamePrompt {
            get {
                return ResourceManager.GetString("DeleteGamePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete genre?.
        /// </summary>
        internal static string DeleteGenrePrompt {
            get {
                return ResourceManager.GetString("DeleteGenrePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete image?.
        /// </summary>
        internal static string DeleteImagePrompt {
            get {
                return ResourceManager.GetString("DeleteImagePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на An error occured..
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The program&apos;s executable file could not be found. The lazy ass admin should have set the proper file path..
        /// </summary>
        internal static string ExeNotFound {
            get {
                return ResourceManager.GetString("ExeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fill in all the reqiured textfields..
        /// </summary>
        internal static string FillInNecessaryTextBox {
            get {
                return ResourceManager.GetString("FillInNecessaryTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Game added successfully..
        /// </summary>
        internal static string GameAddedToDB {
            get {
                return ResourceManager.GetString("GameAddedToDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The login-password combination could not be found. Contact the admin to register an account..
        /// </summary>
        internal static string LoginPasswordNotFound {
            get {
                return ResourceManager.GetString("LoginPasswordNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Multiplayer.
        /// </summary>
        internal static string Multiplayer {
            get {
                return ResourceManager.GetString("Multiplayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на My games.
        /// </summary>
        internal static string MyGames {
            get {
                return ResourceManager.GetString("MyGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The name is already used..
        /// </summary>
        internal static string NameAlreadyUsed {
            get {
                return ResourceManager.GetString("NameAlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The name is not entered..
        /// </summary>
        internal static string NameNotEntered {
            get {
                return ResourceManager.GetString("NameNotEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rename developer?.
        /// </summary>
        internal static string RenameDeveloperPrompt {
            get {
                return ResourceManager.GetString("RenameDeveloperPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rename genre?.
        /// </summary>
        internal static string RenameGenrePrompt {
            get {
                return ResourceManager.GetString("RenameGenrePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search games.
        /// </summary>
        internal static string SearchGames {
            get {
                return ResourceManager.GetString("SearchGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select the genre to rename and input the new name..
        /// </summary>
        internal static string SelectAGenreNTypeTheName {
            get {
                return ResourceManager.GetString("SelectAGenreNTypeTheName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select the genre to delete..
        /// </summary>
        internal static string SelectAGenreToDelete {
            get {
                return ResourceManager.GetString("SelectAGenreToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sent successfully..
        /// </summary>
        internal static string SentSuccessfully {
            get {
                return ResourceManager.GetString("SentSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Single player.
        /// </summary>
        internal static string SinglePlayer {
            get {
                return ResourceManager.GetString("SinglePlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Subscribe.
        /// </summary>
        internal static string Subscribe {
            get {
                return ResourceManager.GetString("Subscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unsubscribe.
        /// </summary>
        internal static string Unsubscribe {
            get {
                return ResourceManager.GetString("Unsubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel subscription?.
        /// </summary>
        internal static string UnsubscribePrompt {
            get {
                return ResourceManager.GetString("UnsubscribePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Update account?.
        /// </summary>
        internal static string UpdateAccountPrompt {
            get {
                return ResourceManager.GetString("UpdateAccountPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Updated successfully..
        /// </summary>
        internal static string UpdatedSuccessfully {
            get {
                return ResourceManager.GetString("UpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Update game info?.
        /// </summary>
        internal static string UpdateGamePrompt {
            get {
                return ResourceManager.GetString("UpdateGamePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Seems like your account has been suspended. The admin has more info..
        /// </summary>
        internal static string YouAreBanned {
            get {
                return ResourceManager.GetString("YouAreBanned", resourceCulture);
            }
        }
    }
}
